<?php
/**
 * Central registry for published Groot Academy blog guides.
 *
 * Add each new published blog here once. The blog hub and shared article
 * layout use this registry for discovery and related-guide links.
 */
return [
    'it-career-course-guidance-jaipur' => [
        'title' => 'IT Career Course Guidance for Students in Jaipur',
        'slug' => 'it-career-course-guidance-jaipur',
        'description' => 'Choose a learning path across programming, development, analytics and digital marketing.',
        'category' => 'Career Guidance',
        'related' => ['software-development-coding-career-guide-jaipur', 'data-analytics-power-bi-career-guide-jaipur', 'digital-marketing-career-guide-jaipur'],
    ],
    'software-development-coding-career-guide-jaipur' => [
        'title' => 'Software Development and Coding Career Guidance in Jaipur',
        'slug' => 'software-development-coding-career-guide-jaipur',
        'description' => 'Build programming fundamentals and move toward frontend, backend or full stack development.',
        'category' => 'Software Development',
        'related' => ['python-programming-career-guide-jaipur', 'java-programming-software-development-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'data-analytics-power-bi-career-guide-jaipur' => [
        'title' => 'Data Analytics and Power BI Career Guidance in Jaipur',
        'slug' => 'data-analytics-power-bi-career-guide-jaipur',
        'description' => 'Learn a practical roadmap with Excel, SQL, Power BI, Python and real datasets.',
        'category' => 'Data Analytics',
        'related' => ['excel-advanced-excel-career-guide-jaipur', 'sql-database-career-guide-jaipur', 'power-bi-business-intelligence-career-guide-jaipur'],
    ],
    'power-bi-business-intelligence-career-guide-jaipur' => [
        'title' => 'Power BI and Business Intelligence Career Guidance in Jaipur',
        'slug' => 'power-bi-business-intelligence-career-guide-jaipur',
        'description' => 'Build Power Query, data modelling, DAX, dashboard, KPI and business reporting skills with practical BI projects.',
        'category' => 'Business Intelligence',
        'related' => ['data-analytics-power-bi-career-guide-jaipur', 'excel-advanced-excel-career-guide-jaipur', 'sql-database-career-guide-jaipur'],
    ],
    'data-science-machine-learning-career-guide-jaipur' => [
        'title' => 'Data Science and Machine Learning Career Guidance in Jaipur',
        'slug' => 'data-science-machine-learning-career-guide-jaipur',
        'description' => 'Move from Python, SQL and statistics into data analysis, machine learning and practical model projects.',
        'category' => 'Data Science & Machine Learning',
        'related' => ['python-programming-career-guide-jaipur', 'data-analytics-power-bi-career-guide-jaipur', 'generative-ai-tools-career-guide-jaipur'],
    ],
    'generative-ai-tools-career-guide-jaipur' => [
        'title' => 'Generative AI and AI Tools Career Guidance in Jaipur',
        'slug' => 'generative-ai-tools-career-guide-jaipur',
        'description' => 'Explore prompt engineering, Python, APIs, LLM basics, AI tools, automation and practical AI projects.',
        'category' => 'Generative AI',
        'related' => ['data-science-machine-learning-career-guide-jaipur', 'python-programming-career-guide-jaipur', 'software-development-coding-career-guide-jaipur'],
    ],
    'digital-marketing-career-guide-jaipur' => [
        'title' => 'Digital Marketing Career Guidance for Beginners in Jaipur',
        'slug' => 'digital-marketing-career-guide-jaipur',
        'description' => 'Explore SEO, social media, paid ads, content, email marketing and analytics.',
        'category' => 'Digital Marketing',
        'related' => ['it-career-course-guidance-jaipur', 'data-analytics-power-bi-career-guide-jaipur', 'web-designing-frontend-development-jaipur'],
    ],
    'full-stack-web-development-career-guide-jaipur' => [
        'title' => 'Full Stack Web Development Career Guidance in Jaipur',
        'slug' => 'full-stack-web-development-career-guide-jaipur',
        'description' => 'Learn frontend, backend, databases, APIs, Git and complete web application development.',
        'category' => 'Full Stack Development',
        'related' => ['mern-stack-react-development-career-guide-jaipur', 'web-designing-frontend-development-jaipur', 'sql-database-career-guide-jaipur'],
    ],
    'python-programming-career-guide-jaipur' => [
        'title' => 'Python Programming Career Guidance for Beginners in Jaipur',
        'slug' => 'python-programming-career-guide-jaipur',
        'description' => 'Start with Python fundamentals and move into projects, web development, analytics and automation.',
        'category' => 'Python Programming',
        'related' => ['data-science-machine-learning-career-guide-jaipur', 'software-development-coding-career-guide-jaipur', 'data-analytics-power-bi-career-guide-jaipur'],
    ],
    'java-programming-software-development-jaipur' => [
        'title' => 'Java Programming and Software Development Career Guide in Jaipur',
        'slug' => 'java-programming-software-development-jaipur',
        'description' => 'Build Core Java skills, then progress to JDBC, SQL, Spring Boot and REST APIs.',
        'category' => 'Java Programming',
        'related' => ['software-development-coding-career-guide-jaipur', 'sql-database-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'mern-stack-react-development-career-guide-jaipur' => [
        'title' => 'MERN Stack and React Development Career Guidance in Jaipur',
        'slug' => 'mern-stack-react-development-career-guide-jaipur',
        'description' => 'Learn JavaScript, React, Node.js, Express, MongoDB and full stack project development.',
        'category' => 'MERN Stack',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'web-designing-frontend-development-jaipur', 'software-development-coding-career-guide-jaipur'],
    ],
    'sql-database-career-guide-jaipur' => [
        'title' => 'SQL and Database Career Guidance for Students in Jaipur',
        'slug' => 'sql-database-career-guide-jaipur',
        'description' => 'Build database skills with queries, joins, subqueries, CRUD operations and practical datasets.',
        'category' => 'SQL & Databases',
        'related' => ['data-analytics-power-bi-career-guide-jaipur', 'excel-advanced-excel-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'web-designing-frontend-development-jaipur' => [
        'title' => 'Web Designing and Frontend Development Career Guide in Jaipur',
        'slug' => 'web-designing-frontend-development-jaipur',
        'description' => 'Learn HTML, CSS, responsive design, Bootstrap, JavaScript, UI basics and website projects.',
        'category' => 'Web Designing',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'mern-stack-react-development-career-guide-jaipur', 'digital-marketing-career-guide-jaipur'],
    ],
    'c-cpp-dsa-career-guide-jaipur' => [
        'title' => 'C, C++ and Data Structures Career Guidance in Jaipur',
        'slug' => 'c-cpp-dsa-career-guide-jaipur',
        'description' => 'Strengthen programming logic, OOP, Data Structures and Algorithms through coding practice.',
        'category' => 'C, C++ & DSA',
        'related' => ['software-development-coding-career-guide-jaipur', 'java-programming-software-development-jaipur', 'python-programming-career-guide-jaipur'],
    ],
    'excel-advanced-excel-career-guide-jaipur' => [
        'title' => 'Excel and Advanced Excel Career Guidance in Jaipur',
        'slug' => 'excel-advanced-excel-career-guide-jaipur',
        'description' => 'Learn formulas, lookups, Pivot Tables, dashboards, data cleaning and business reporting.',
        'category' => 'Excel & Reporting',
        'related' => ['data-analytics-power-bi-career-guide-jaipur', 'power-bi-business-intelligence-career-guide-jaipur', 'sql-database-career-guide-jaipur'],
    ],
    'cloud-computing-aws-career-guide-jaipur' => [
        'title' => 'Cloud Computing and AWS Career Guidance in Jaipur',
        'slug' => 'cloud-computing-aws-career-guide-jaipur',
        'description' => 'Learn cloud foundations, Linux, networking, IAM, EC2, S3, databases and practical AWS deployment workflows.',
        'category' => 'Cloud Computing',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'software-development-coding-career-guide-jaipur', 'python-programming-career-guide-jaipur'],
    ],
    'devops-ci-cd-career-guide-jaipur' => [
        'title' => 'DevOps and CI/CD Career Guidance in Jaipur',
        'slug' => 'devops-ci-cd-career-guide-jaipur',
        'description' => 'Learn Linux, Git, Docker, CI/CD, cloud deployment, monitoring and automation through practical DevOps projects.',
        'category' => 'DevOps',
        'related' => ['cloud-computing-aws-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur', 'software-development-coding-career-guide-jaipur'],
    ],
    'cyber-security-ethical-hacking-career-guide-jaipur' => [
        'title' => 'Cyber Security and Ethical Hacking Career Guidance in Jaipur',
        'slug' => 'cyber-security-ethical-hacking-career-guide-jaipur',
        'description' => 'Learn networking, Linux, web security, monitoring and ethical hacking concepts through authorised practical labs.',
        'category' => 'Cyber Security',
        'related' => ['cloud-computing-aws-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur', 'software-development-coding-career-guide-jaipur'],
    ],
    'flutter-mobile-app-development-career-guide-jaipur' => [
        'title' => 'Flutter and Mobile App Development Career Guidance in Jaipur',
        'slug' => 'flutter-mobile-app-development-career-guide-jaipur',
        'description' => 'Learn Dart, Flutter widgets, responsive UI, navigation, APIs, Firebase and practical mobile app development.',
        'category' => 'Mobile App Development',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'software-development-coding-career-guide-jaipur', 'ui-ux-design-career-guide-jaipur'],
    ],
    'graphic-design-career-guide-jaipur' => [
        'title' => 'Graphic Design Career Guidance in Jaipur',
        'slug' => 'graphic-design-career-guide-jaipur',
        'description' => 'Learn design fundamentals, Photoshop, Illustrator, Canva, branding, social media creatives and portfolio development.',
        'category' => 'Graphic Design',
        'related' => ['ui-ux-design-career-guide-jaipur', 'digital-marketing-career-guide-jaipur', 'web-designing-frontend-development-jaipur'],
    ],
    'video-editing-motion-graphics-career-guide-jaipur' => [
        'title' => 'Video Editing and Motion Graphics Career Guidance in Jaipur',
        'slug' => 'video-editing-motion-graphics-career-guide-jaipur',
        'description' => 'Learn video editing fundamentals, Premiere Pro, After Effects, audio, colour, motion graphics and portfolio development.',
        'category' => 'Video Editing',
        'related' => ['graphic-design-career-guide-jaipur', 'digital-marketing-career-guide-jaipur', 'ui-ux-design-career-guide-jaipur'],
    ],
    'wordpress-website-development-career-guide-jaipur' => [
        'title' => 'WordPress Website Development Career Guidance in Jaipur',
        'slug' => 'wordpress-website-development-career-guide-jaipur',
        'description' => 'Learn WordPress setup, themes, plugins, Elementor, WooCommerce, SEO basics and practical website development.',
        'category' => 'WordPress Development',
        'related' => ['web-designing-frontend-development-jaipur', 'digital-marketing-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'software-testing-qa-automation-career-guide-jaipur' => [
        'title' => 'Software Testing, QA and Automation Career Guidance in Jaipur',
        'slug' => 'software-testing-qa-automation-career-guide-jaipur',
        'description' => 'Learn manual testing, test cases, bug reporting, API testing, SQL, Selenium basics and automation fundamentals.',
        'category' => 'Software Testing & QA',
        'related' => ['software-development-coding-career-guide-jaipur', 'java-programming-software-development-jaipur', 'devops-ci-cd-career-guide-jaipur'],
    ],
    'php-mysql-backend-development-career-guide-jaipur' => [
        'title' => 'PHP, MySQL and Backend Development Career Guidance in Jaipur',
        'slug' => 'php-mysql-backend-development-career-guide-jaipur',
        'description' => 'Learn PHP, MySQL, forms, sessions, CRUD, authentication, APIs and practical backend web application development.',
        'category' => 'Backend Development',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'sql-database-career-guide-jaipur', 'wordpress-website-development-career-guide-jaipur'],
    ],
    'django-python-web-development-career-guide-jaipur' => [
        'title' => 'Django and Python Web Development Career Guidance in Jaipur',
        'slug' => 'django-python-web-development-career-guide-jaipur',
        'description' => 'Learn Python web development with Django, templates, models, forms, authentication, APIs and practical projects.',
        'category' => 'Python Web Development',
        'related' => ['python-programming-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur', 'sql-database-career-guide-jaipur'],
    ],
    'deep-learning-neural-networks-career-guide-jaipur' => [
        'title' => 'Deep Learning and Neural Networks Career Guidance in Jaipur',
        'slug' => 'deep-learning-neural-networks-career-guide-jaipur',
        'description' => 'Learn Python, neural networks, TensorFlow, Keras, CNNs, sequence models and practical Deep Learning projects.',
        'category' => 'Deep Learning',
        'related' => ['data-science-machine-learning-career-guide-jaipur', 'python-programming-career-guide-jaipur', 'generative-ai-tools-career-guide-jaipur'],
    ],
    'linux-system-administration-career-guide-jaipur' => [
        'title' => 'Linux and System Administration Career Guidance in Jaipur',
        'slug' => 'linux-system-administration-career-guide-jaipur',
        'description' => 'Learn Linux commands, users, permissions, processes, networking, services, logs and shell scripting through practical labs.',
        'category' => 'Linux & System Administration',
        'related' => ['devops-ci-cd-career-guide-jaipur', 'cloud-computing-aws-career-guide-jaipur', 'cyber-security-ethical-hacking-career-guide-jaipur'],
    ],
    'git-github-version-control-career-guide-jaipur' => [
        'title' => 'Git and GitHub Version Control Career Guidance in Jaipur',
        'slug' => 'git-github-version-control-career-guide-jaipur',
        'description' => 'Learn repositories, commits, branches, merges, pull requests, conflict resolution and collaborative coding workflows.',
        'category' => 'Git & GitHub',
        'related' => ['software-development-coding-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'computer-networking-ccna-career-guide-jaipur' => [
        'title' => 'Computer Networking and CCNA Career Guidance in Jaipur',
        'slug' => 'computer-networking-ccna-career-guide-jaipur',
        'description' => 'Learn TCP/IP, subnetting, switching, routing, VLANs, DHCP, DNS and troubleshooting through practical network labs.',
        'category' => 'Computer Networking',
        'related' => ['linux-system-administration-career-guide-jaipur', 'cyber-security-ethical-hacking-career-guide-jaipur', 'cloud-computing-aws-career-guide-jaipur'],
    ],
    'rest-api-development-postman-career-guide-jaipur' => [
        'title' => 'REST API Development and Postman Career Guidance in Jaipur',
        'slug' => 'rest-api-development-postman-career-guide-jaipur',
        'description' => 'Learn HTTP methods, JSON, status codes, RESTful endpoints, Postman, authentication and backend API integration.',
        'category' => 'API Development',
        'related' => ['full-stack-web-development-career-guide-jaipur', 'php-mysql-backend-development-career-guide-jaipur', 'django-python-web-development-career-guide-jaipur'],
    ],
    'kubernetes-container-orchestration-career-guide-jaipur' => [
        'title' => 'Kubernetes and Container Orchestration Career Guidance in Jaipur',
        'slug' => 'kubernetes-container-orchestration-career-guide-jaipur',
        'description' => 'Learn containers, pods, deployments, services, configuration, scaling and practical Kubernetes workflows.',
        'category' => 'Kubernetes & Containers',
        'related' => ['devops-ci-cd-career-guide-jaipur', 'cloud-computing-aws-career-guide-jaipur', 'linux-system-administration-career-guide-jaipur'],
    ],
    'docker-containerization-career-guide-jaipur' => [
        'title' => 'Docker and Containerization Career Guidance in Jaipur',
        'slug' => 'docker-containerization-career-guide-jaipur',
        'description' => 'Learn Docker images, containers, Dockerfiles, ports, volumes, networks, Docker Compose and practical deployment workflows.',
        'category' => 'Docker & Containers',
        'related' => ['kubernetes-container-orchestration-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur', 'cloud-computing-aws-career-guide-jaipur'],
    ],
    'mongodb-nosql-database-career-guide-jaipur' => [
        'title' => 'MongoDB and NoSQL Database Career Guidance in Jaipur',
        'slug' => 'mongodb-nosql-database-career-guide-jaipur',
        'description' => 'Learn MongoDB collections, documents, CRUD, queries, indexing, aggregation and backend database integration.',
        'category' => 'MongoDB & NoSQL',
        'related' => ['mern-stack-react-development-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur', 'sql-database-career-guide-jaipur'],
    ],
    'spring-boot-microservices-career-guide-jaipur' => [
        'title' => 'Spring Boot and Microservices Career Guidance in Jaipur',
        'slug' => 'spring-boot-microservices-career-guide-jaipur',
        'description' => 'Learn Spring Boot, REST APIs, JPA, database integration, validation, security basics and microservices concepts.',
        'category' => 'Spring Boot & Microservices',
        'related' => ['java-programming-software-development-jaipur', 'rest-api-development-postman-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur'],
    ],
    'typescript-modern-javascript-career-guide-jaipur' => [
        'title' => 'TypeScript and Modern JavaScript Career Guidance in Jaipur',
        'slug' => 'typescript-modern-javascript-career-guide-jaipur',
        'description' => 'Learn modern JavaScript, TypeScript types, interfaces, generics, modules, async code and practical frontend/backend development.',
        'category' => 'TypeScript & JavaScript',
        'related' => ['mern-stack-react-development-career-guide-jaipur', 'full-stack-web-development-career-guide-jaipur', 'rest-api-development-postman-career-guide-jaipur'],
    ],
    'angular-frontend-development-career-guide-jaipur' => [
        'title' => 'Angular Frontend Development Career Guidance in Jaipur',
        'slug' => 'angular-frontend-development-career-guide-jaipur',
        'description' => 'Learn TypeScript, Angular components, routing, forms, services, APIs, RxJS basics and practical frontend development.',
        'category' => 'Angular Development',
        'related' => ['typescript-modern-javascript-career-guide-jaipur', 'web-designing-frontend-development-jaipur', 'rest-api-development-postman-career-guide-jaipur'],
    ],
    'firebase-backend-as-a-service-career-guide-jaipur' => [
        'title' => 'Firebase and Backend-as-a-Service Career Guidance in Jaipur',
        'slug' => 'firebase-backend-as-a-service-career-guide-jaipur',
        'description' => 'Learn Firebase Authentication, Firestore, Storage, Hosting, Security Rules and practical cloud-connected application development.',
        'category' => 'Firebase & BaaS',
        'related' => ['flutter-mobile-app-development-career-guide-jaipur', 'angular-frontend-development-career-guide-jaipur', 'rest-api-development-postman-career-guide-jaipur'],
    ],
    'graphql-api-apollo-career-guide-jaipur' => [
        'title' => 'GraphQL API and Apollo Career Guidance in Jaipur',
        'slug' => 'graphql-api-apollo-career-guide-jaipur',
        'description' => 'Learn GraphQL schemas, queries, mutations, resolvers, Apollo, authentication basics and practical API integration.',
        'category' => 'GraphQL & APIs',
        'related' => ['rest-api-development-postman-career-guide-jaipur', 'typescript-modern-javascript-career-guide-jaipur', 'mongodb-nosql-database-career-guide-jaipur'],
    ],
    'nextjs-full-stack-react-career-guide-jaipur' => [
        'title' => 'Next.js Full Stack React Career Guidance in Jaipur',
        'slug' => 'nextjs-full-stack-react-career-guide-jaipur',
        'description' => 'Learn React, Next.js App Router, server components, data fetching, API routes, authentication and deployment.',
        'category' => 'Next.js & React',
        'related' => ['mern-stack-react-development-career-guide-jaipur', 'typescript-modern-javascript-career-guide-jaipur', 'rest-api-development-postman-career-guide-jaipur'],
    ],
    'react-native-mobile-app-development-career-guide-jaipur' => [
        'title' => 'React Native Mobile App Development Career Guidance in Jaipur',
        'slug' => 'react-native-mobile-app-development-career-guide-jaipur',
        'description' => 'Learn JavaScript, React Native components, navigation, APIs, state, Firebase and cross-platform mobile app development.',
        'category' => 'React Native',
        'related' => ['typescript-modern-javascript-career-guide-jaipur', 'firebase-backend-as-a-service-career-guide-jaipur', 'flutter-mobile-app-development-career-guide-jaipur'],
    ],
    'nodejs-express-backend-development-career-guide-jaipur' => [
        'title' => 'Node.js and Express Backend Development Career Guidance in Jaipur',
        'slug' => 'nodejs-express-backend-development-career-guide-jaipur',
        'description' => 'Learn Node.js, Express, REST APIs, middleware, authentication, MongoDB/SQL integration and practical backend development.',
        'category' => 'Node.js & Express',
        'related' => ['rest-api-development-postman-career-guide-jaipur', 'mongodb-nosql-database-career-guide-jaipur', 'typescript-modern-javascript-career-guide-jaipur'],
    ],
    'python-automation-scripting-career-guide-jaipur' => [
        'title' => 'Python Automation and Scripting Career Guidance in Jaipur',
        'slug' => 'python-automation-scripting-career-guide-jaipur',
        'description' => 'Learn Python scripting for files, Excel, APIs, data processing, scheduling, logging and practical workflow automation.',
        'category' => 'Python Automation',
        'related' => ['python-programming-career-guide-jaipur', 'rest-api-development-postman-career-guide-jaipur', 'data-analytics-power-bi-career-guide-jaipur'],
    ],
    'fastapi-python-backend-development-career-guide-jaipur' => [
        'title' => 'FastAPI Python Backend Development Career Guidance in Jaipur',
        'slug' => 'fastapi-python-backend-development-career-guide-jaipur',
        'description' => 'Learn FastAPI, REST APIs, request validation, databases, authentication, async concepts and practical Python backend development.',
        'category' => 'FastAPI & Python Backend',
        'related' => ['python-programming-career-guide-jaipur', 'rest-api-development-postman-career-guide-jaipur', 'django-python-web-development-career-guide-jaipur'],
    ],
    'computer-vision-opencv-career-guide-jaipur' => [
        'title' => 'Computer Vision and OpenCV Career Guidance in Jaipur',
        'slug' => 'computer-vision-opencv-career-guide-jaipur',
        'description' => 'Learn Python, OpenCV, image processing, video analysis, detection concepts, CNN basics and practical Computer Vision projects.',
        'category' => 'Computer Vision & OpenCV',
        'related' => ['deep-learning-neural-networks-career-guide-jaipur', 'data-science-machine-learning-career-guide-jaipur', 'python-programming-career-guide-jaipur'],
    ],
    'helm-kubernetes-package-manager-career-guide-jaipur' => [
        'title' => 'Helm and Kubernetes Package Management Career Guidance in Jaipur',
        'slug' => 'helm-kubernetes-package-manager-career-guide-jaipur',
        'description' => 'Learn Helm charts, values, templates, releases, repositories, upgrades, rollbacks and reusable Kubernetes deployments.',
        'category' => 'Helm & Kubernetes',
        'related' => ['kubernetes-container-orchestration-career-guide-jaipur', 'docker-containerization-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur'],
    ],
    'jenkins-ci-cd-automation-career-guide-jaipur' => [
        'title' => 'Jenkins CI/CD Automation Career Guidance in Jaipur',
        'slug' => 'jenkins-ci-cd-automation-career-guide-jaipur',
        'description' => 'Learn Jenkins pipelines, Jenkinsfile, Git integration, builds, testing, Docker and practical CI/CD automation.',
        'category' => 'Jenkins & CI/CD',
        'related' => ['devops-ci-cd-career-guide-jaipur', 'docker-containerization-career-guide-jaipur', 'git-github-version-control-career-guide-jaipur'],
    ],
    'argocd-gitops-kubernetes-continuous-delivery-career-guide-jaipur' => [
        'title' => 'Argo CD, GitOps and Kubernetes Continuous Delivery Career Guidance in Jaipur',
        'slug' => 'argocd-gitops-kubernetes-continuous-delivery-career-guide-jaipur',
        'description' => 'Learn GitOps, Argo CD sync, rollback, health checks, Helm integration and Kubernetes continuous delivery.',
        'category' => 'Argo CD & GitOps',
        'related' => ['kubernetes-container-orchestration-career-guide-jaipur', 'helm-kubernetes-package-manager-career-guide-jaipur', 'jenkins-ci-cd-automation-career-guide-jaipur'],
    ],
    'hashicorp-vault-secrets-management-devops-security-career-guide-jaipur' => [
        'title' => 'HashiCorp Vault, Secrets Management & DevOps Security Career Guidance in Jaipur',
        'slug' => 'hashicorp-vault-secrets-management-devops-security-career-guide-jaipur',
        'description' => 'Learn Vault policies, tokens, secrets engines, dynamic credentials, encryption and secure Kubernetes/CI-CD integrations.',
        'category' => 'Vault & DevOps Security',
        'related' => ['terraform-infrastructure-as-code-devops-career-guide-jaipur', 'kubernetes-container-orchestration-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur'],
    ],
    'github-actions-ci-cd-workflow-automation-career-guide-jaipur' => [
        'title' => 'GitHub Actions CI/CD & Workflow Automation Career Guidance in Jaipur',
        'slug' => 'github-actions-ci-cd-workflow-automation-career-guide-jaipur',
        'description' => 'Learn GitHub Actions workflows, jobs, runners, secrets, automated testing, Docker builds and deployment pipelines.',
        'category' => 'GitHub Actions & CI/CD',
        'related' => ['git-github-version-control-career-guide-jaipur', 'jenkins-ci-cd-automation-career-guide-jaipur', 'docker-containerization-career-guide-jaipur'],
    ],
    'sonarqube-code-quality-devsecops-static-analysis-career-guide-jaipur' => [
        'title' => 'SonarQube, Code Quality & DevSecOps Career Guidance in Jaipur',
        'slug' => 'sonarqube-code-quality-devsecops-static-analysis-career-guide-jaipur',
        'description' => 'Learn static code analysis, bugs, code smells, security hotspots, quality gates and CI/CD integration with SonarQube.',
        'category' => 'SonarQube & DevSecOps',
        'related' => ['jenkins-ci-cd-automation-career-guide-jaipur', 'github-actions-ci-cd-workflow-automation-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur'],
    ],
    'trivy-container-security-devsecops-vulnerability-scanning-career-guide-jaipur' => [
        'title' => 'Trivy, Container Security & DevSecOps Vulnerability Scanning Career Guidance in Jaipur',
        'slug' => 'trivy-container-security-devsecops-vulnerability-scanning-career-guide-jaipur',
        'description' => 'Learn Trivy container scanning, dependency checks, IaC misconfiguration scanning and CI/CD security gates.',
        'category' => 'Trivy & DevSecOps Security',
        'related' => ['docker-containerization-career-guide-jaipur', 'kubernetes-container-orchestration-career-guide-jaipur', 'sonarqube-code-quality-devsecops-static-analysis-career-guide-jaipur'],
    ],
    'snyk-dependency-security-sca-devsecops-career-guide-jaipur' => [
        'title' => 'Snyk, Dependency Security & Software Composition Analysis Career Guidance in Jaipur',
        'slug' => 'snyk-dependency-security-sca-devsecops-career-guide-jaipur',
        'description' => 'Learn Snyk dependency scanning, software composition analysis, open-source risk, license checks and CI/CD integration.',
        'category' => 'Snyk & Dependency Security',
        'related' => ['trivy-container-security-devsecops-vulnerability-scanning-career-guide-jaipur', 'sonarqube-code-quality-devsecops-static-analysis-career-guide-jaipur', 'github-actions-ci-cd-workflow-automation-career-guide-jaipur'],
    ],
    'owasp-zap-dast-web-application-security-testing-career-guide-jaipur' => [
        'title' => 'OWASP ZAP, DAST & Web Application Security Testing Career Guidance in Jaipur',
        'slug' => 'owasp-zap-dast-web-application-security-testing-career-guide-jaipur',
        'description' => 'Learn OWASP ZAP proxy testing, passive and active scanning, alert review and CI/CD web security checks.',
        'category' => 'OWASP ZAP & DAST',
        'related' => ['cyber-security-ethical-hacking-career-guide-jaipur', 'sonarqube-code-quality-devsecops-static-analysis-career-guide-jaipur', 'trivy-container-security-devsecops-vulnerability-scanning-career-guide-jaipur'],
    ],
    'nginx-reverse-proxy-load-balancing-web-server-career-guide-jaipur' => [
        'title' => 'Nginx, Reverse Proxy & Load Balancing Career Guidance in Jaipur',
        'slug' => 'nginx-reverse-proxy-load-balancing-web-server-career-guide-jaipur',
        'description' => 'Learn Nginx web-server setup, reverse proxy, load balancing, SSL, caching and practical deployment workflows.',
        'category' => 'Nginx & Web Infrastructure',
        'related' => ['linux-system-administration-career-guide-jaipur', 'docker-containerization-career-guide-jaipur', 'devops-ci-cd-career-guide-jaipur'],
    ],
];
